version: '3.8'

services:
  app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - db
    command: ["java", "-jar", "/app/app.jar"]

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Nam12345678@"
      MSSQL_PID: "Express" # Optional: Specify the edition
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: