package com.g3.Jewelry_Auction_System.entity;

public enum ERequestStatus {
    PENDING,
    PRELIMINARY_VALUATION_IN_PROGRESS,
    AWAITING_APPROVAL,
    AWATING_CONSIGNMENT,
    JEWELRY_RECEIVED,
    FINAL_VALUATION_IN_PROGRESS,
    COMPLETED,
    CANCELED
}
